### ISSUE TITLE
problem adding a task on a date that does not exist in the month

### ISSUE THREAD

**Issue by JavynThun** [CS2103AUG2017-T11-B3/main#109]
when i tried "add money by 32 dec" the task deadline that was added was 1 dec '48 instead of showing invalid date

**Comment by tpq95** [comment]
hi sorry, but in the task mode, add will require date to have month before day, however it can be any format, i.e mm-DD-yyyy, mm.dd.yy etc..

thanks for the feedback, will specify more in the guide

**Comment by raisa2010** [comment]
Hello, thank you for the review! I'm aware of the issue and it has to do with the natural language parser not throwing errors in case an invalid date is specified. Trying to schedule something on 12/32/2017 will still give you a warning!

**Comment by tpq95** [comment]
<img width="386" alt="screen shot 2017-11-03 at 3 36 02 pm" src="https://user-images.githubusercontent.com/31122808/32363922-c2ce1800-c0ac-11e7-994c-9e9f5fdf192a.png">

- invalid date is shown
- just format of date should be month before day
- add to to-do: to update the command guide

**Comment by tpq95** [comment]
**update**
- date in normal format, i.e digits: 01-32-2017 will flag invalid date
- date in phrase format, i.e Jan, 32 will not be flagged

**TO-DO**
- [ ] resolves pretty time parser

**Comment by raisa2010** [comment]
So I asked our tutor and he said it isn't necessary to fix this since it's a limitation in the library and not the code.

**Comment by tpq95** [comment]
Alright, then pls include it as a note in ug. Thanks and I am closing this.
