### ISSUE TITLE
Acceptance Testing

### ISSUE THREAD

**Issue by Kennard123661** [CS2103AUG2017-T11-B3/main#111]
Hi, 

Sorry that this was a little late, but here's the results of my acceptance testing. Sorry it took awhile, was debugging some of my features on my app. 

![image](https://user-images.githubusercontent.com/17818981/32383622-728dc7fe-c0f3-11e7-9fec-9b801e1042d5.png)

Change the cursor icon when you mouse over this region, the cursor changes to a draggable cursor, but the region is not draggable 

* When typing in add command, the help box just shows the first prefix n/ but does not show the rest. 

![image](https://user-images.githubusercontent.com/17818981/32383873-2a1bc98e-c0f4-11e7-9e9d-6f81d187518b.png)

* I can't seem to add tasks.  (At this point, I guess the task manager segment has not been implemented yet.

![image](https://user-images.githubusercontent.com/17818981/32383942-5c5bafae-c0f4-11e7-8b8f-bf711d9bb767.png)

* What is this blank region for? Oo

* There is a delay as to when the helper box is shown to help you type in commands, might be abit too delayed to be of significant use atm. Maybe can try improving its time complexity? Are you guys using a library for that btw? 

* Also, the calendar feels like it was extracted from some place outside of the addressbook and paste itself, maybe make it seem like its a part of the addressbook by changing its colour scheme (just a suggestion)

* When I click the calendar, the list view disappears, I think its because you want to implement a list of tasks there? Am I correct? 

All in all, I think you guys are doing great!

**Comment by raisa2010** [comment]
Hello! Thank you for our review!

The add task command has been implemented. I'm not sure if you've switched modes however? Try typing in "switch tm" before using the add task command.

The blank region is for the task list!

Yep the help box uses the controlsfx library. It's just a one liner method so I'm not sure why it's slow or whether it can be fixed in our code (might be an issue with the library?)

Thank you for the suggestions!

**Comment by tpq95** [comment]
The listed cards disappears as there is no deadline/birthday that corresponds to the date clicked on the calendar.

Thanks for the review!

Closing this issue and separating it into individual bugs to solve..
