### ISSUE TITLE
Create SampleData.xml

### ISSUE THREAD

**Issue by tpq95** [CS2103AUG2017-T11-B3/main#125]
- [x] create `SampleData.xml` with at least 20 items for AB and TM, 
in {project root}\src\test\data\ManualTesting\[T11-B3][Mobilize]SampleData.xml

- [ ] upload to IVLE

**Comment by raisa2010** [comment]
Shall we just post about 7-10 add commands each for tm and ab here so you can input them into your app and upload the xml file generated in the data folder?

**Comment by raisa2010** [comment]
Actually that sounds too tedious. If we add our info the SampleDataUtil class and upload to a different branch on gh, you can pull from it, delete your existing xml file and run the app. All the data should be inserted already in the auto-generated xml file and you can send us the doc to verify and upload.
