### ISSUE TITLE
Create TestScript.adoc

### ISSUE THREAD

**Issue by tpq95** [CS2103AUG2017-T11-B3/main#126]
- [ ] create `TestScript.adoc` as
*{project root}\src\test\data\ManualTesting\[T11-B3][Mobilize]TestScript.adoc*
__Guide__- A document explaining the steps to perform manual testing (i.e. manual scripted testing), starting with how to load the sample data.
Should cover all functionality of the product. 
Should be grouped by functionality.
Should specify the command to type and the expected result (screenshots not required).
Limit the test cases to about 20 minutes worth of testing.

- [ ] upload to IVLE

**Comment by raisa2010** [comment]
If everyone covers the testing for their own feature, I can compile them.
