### ISSUE TITLE
Finalise demo

### ISSUE THREAD

**Issue by tpq95** [CS2103AUG2017-T11-B3/main#129]
- [x] decide on demo flow

- [x] read up CS2103 website for more details

- [x] decide dress code

- [x] decide slogan

- [x] bring data for testing

- [x] date to rehearse (important la!)

**Comment by raisa2010** [comment]
Dress code : same as CS2101?
Also, what slogan?

**Comment by raisa2010** [comment]
Rehearsal: we could do one on skype before Wednesday and one face-to-face after the EE2020 exam on Wed.

**Comment by eryao95** [comment]
yeah. same as CS2101. i am ok with the rehearsal that raisa proposed.

**Comment by eryao95** [comment]
how about slogan: Mobilize for easier life
