### ISSUE TITLE
Improvement Suggestions to User Guide

### ISSUE THREAD

**Issue by charlesgoh** [CS2103AUG2017-T11-B3/main#145]
Either some of the documentation was not worded properly or some features need fixing

For example:
The format for adding tasks is:
**Format: add DESCRIPTION [by/on/from DEADLINE] [at START TIME to END TIME] [t/TAG]…**
By following this, I was not able to create a task.

<img width="1401" alt="screen shot 2017-11-17 at 2 39 28 pm" src="https://user-images.githubusercontent.com/15852016/32933606-65066110-cba5-11e7-9909-3b8ba61b3947.png">

Please look into it :)

Also, I don't think the error message should be talking about the adding of persons. Shouldn't it refer to tasks?

**Comment by raisa2010** [comment]
Hi there! I'm sorry for the confusion, you'd have to switch modes to switch tm before being able to access any of the task methods. This was at the top of the User Guide before any of the other features, along the lines of "Switching Command Modes". 

Thank you so much for your review!
