### ISSUE TITLE
Friendly Reminder

### ISSUE THREAD

**Issue by eugenepeh** [CS2103AUG2017-T11-B3/main#22]
User Guide:
Update the user guide to describe what the product would be like when it is at 2.0. Mark features not implemented yet as Coming in v2.0. You may use UI mockups where necessary.

README.md page: Update it to match your project. In particular, add a UI mockup of your intended final product. Note that the image of the UI should be docs/images/Ui.png so that it can be downloaded by our scripts. Also, remember to acknowledge the original source of the code i.e. AddressBook-Level4 project created by SE-EDU initiative at https://github.com/se-edu/ You may remove the Learning Outcomes link and related pages.

About Us page:
This page is used for module admin purposes. Please follow the format closely to avoid penalties.
Replace info of SE-EDU developers with info of your team, including a suitable photo as described here.
Including the name/photo of the supervisor/lecturer is optional. The photo of a team member should be doc/images/githbub_id_in_lower_case.pnge.g. docs/images/damithc.png.

**Comment by raisa2010** [comment]
@eugenepeh How do we figure out how many LoC we've written? Just add up all the +lines in our PR? They could also be just import statements or blank spaces...I'm not sure if that would count?

**Comment by eugenepeh** [comment]
@raisa2010 in Github > Insights > Contributors, it gives you a rough estimate. 
At the end of the project, I believe there will be directions from Prof. asking you to claim the part of the code you wrote and collate them for grading.

**Comment by raisa2010** [comment]
@eugenepeh Okay, thank you

**Comment by tpq95** [comment]
#121
