### ISSUE TITLE
As a user, I can edit a deadline...

### ISSUE THREAD

**Issue by raisa2010** [CS2103AUG2017-T11-B3/main#36]
...so that I can manage changes in my schedule.

**Comment by eugenepeh** [comment]
task? are you guys building a task scheduler? Also for these issues, try to assign people to do it or people who want to do it assign themselves. You also can label it as Features / Bugs etc and Milestone. It helps to show your team's planning.

**Comment by eugenepeh** [comment]
in case you guys missed it @raisa2010 @eryao95 @tby1994 @tpq95 , 

Here's the [project assessment details](https://nus-cs2103.github.io/website/admin/index.html#admin-project-assessment), do take note of 'how well the features implemented fit together '

**Comment by raisa2010** [comment]
@eugenepeh We were thinking of combining the addressbook and a task manager for an all-round personal assistant/manager kind of application? Too much of a stretch? (In terms of fitting features that is)

**Comment by raisa2010** [comment]
Merged to Issue #35
