### ISSUE TITLE
Organisation workflow and management

### ISSUE THREAD

**Issue by eugenepeh** [CS2103AUG2017-T11-B3/main#61]
Hello @raisa2010 @eryao95 @tby1994 @tpq95 ,

I realized that you guys have the tendency to merge your work without it being review by the others. As an organisation you guys should try to get each others to review your own work before merging it. More than often, programmers tend to get blinded by their own logic and assume that the code/program they write will always work. This is why, it is important to get at least another person to review your own work before merging it. 

As a team, you guys should try to adopt this practice, because at the end of the day the quality is as important as the quantity. You can start doing this by enabling going to your `Settings > Branches > Branch Protection for master branch` and enable the following

![image](https://user-images.githubusercontent.com/19277206/31800306-99ca26aa-b572-11e7-87db-a9cb0c9f582c.png)

However, since all of you have owner rights, this might not be useful unless you guys appoint someone who will ensure that this happens. 

Best Regards,
Eugene

P.S don't forget to submit all your changes you want me to review by weekend. Your v1.2 works should have been merged and close by now.

**Comment by raisa2010** [comment]
Hi @eugenepeh , thanks for the tip!

On an unrelated note, however, I'm not sure how we ended up with PR #58 ?

**Comment by eugenepeh** [comment]
hmm? seems like your codacy badger is spying on my old project, that should be under your codacy account setting or a bug.

Well take note that my old project workflow is quite different from current CS2103 requirement and its quite a rushed product. You're welcome to reference it but please do not plagiarize. You will have to refer to how to acknowledge work from other developers in CS2103.

**Comment by raisa2010** [comment]
Hi @eugenepeh,

Do you know how we might change settings so i doesn't happen again possibly?
No intention to plagiarize, I'll just close the PR. Thanks!

**Comment by eugenepeh** [comment]
No worries, I'm not assuming that you're plagiarising, it just a prompt reminder. I'm not sure about that, if the settings isn't found in your codacy account then most probably its a bug. It is constantly reoccurring, you can make a request to disable your codacy in the slack channel.
