### ISSUE TITLE
As an user, i can link person to the task...

### ISSUE THREAD

**Issue by tpq95** [CS2103AUG2017-T11-B3/main#64]
...so that i can know who is involved with the task.

**Comment by raisa2010** [comment]
You can do this by tagging them with the same tag and changing the findTag command so it renders both users and tasks when evoked.

Let me know if that's how you want to proceed because I might have to change the way I add tags to tasks then.

**Comment by tpq95** [comment]
Adding tags to tasks is one alternative and useful to implement. But would it be troublesome to have to tag persons involved and the task added? 

The alternative i was thinking is the adding of 'name-tag' of the person involved for the task. So only one tagging will be done on the task-side, and selecting/finding of task will present a filter list of person involved.

You can also continue with the adding tags like in the address book, and open a new issue. Thanks!

**Comment by raisa2010** [comment]
One extra command? If there's a multiTag option for both people and tasks that is.

Your alternative works too but it would imply only one person can be assigned to a task. If tags are used you can have multiple people assigned to multiple tasks. E.g. #CS2103Project can be used to tag everyone in the team as well as all the tasks related to the project.

**Comment by tpq95** [comment]
I see, in that sense of tagging a group like [tag]cs2103 , it will be easier to implement. As it reduces the need of a new command and new variables in the task. 

Yup so I think you should continue with the adding of tags to the task. Thanks

**Comment by raisa2010** [comment]
PR #69

**Comment by tpq95** [comment]
#100
