### ISSUE TITLE
As an user, i want to have a sorted contacts(sort by names) and tasks(sort by deadline)

### ISSUE THREAD

**Issue by tby1994** [CS2103AUG2017-T11-B3/main#83]

**Comment by raisa2010** [comment]
I'd suggest making tasks sorted by deadline by default. And contacts sorted alphabetically. Instead of adding a whole new command to sort them.

**Comment by tby1994** [comment]
Please read carefully. It’s SORTED not sort.

**Comment by raisa2010** [comment]
I see.

**Comment by eryao95** [comment]
Perhaps raisa you could settle the UGDG first. We can do the code. Thanks

**Comment by raisa2010** [comment]
I've already "settled" my part of the UG/DG. And since the code is 30 percent of the grade, I will also be doing the code. Whether you agree with my suggestions or not is your prerogative.

Please also write a little more clearly if you'd like others to be able to understand.

Thanks.

**Comment by tpq95** [comment]
#101
